version: "3"
services:
    relay:
        build: flask-relay
        ports:
            - 5050:5000
    text_to_speech:
        env_file: tts.env
        build: flite-flask
    game:
        env_file: game.env
        build: game
        ports:
            - 7070:7070
            - 7070:7070/udp
